config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'home#index'
  resources :users, only: %i[index]
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :confirmable,
         :omniauthable, omniauth_providers: %i[github google_oauth2 twitter]
  validates :provider, inclusion: { in: %w[github google_oauth2 twitter] }, allow_nil: true
  validates :uid, uniqueness: { scope: :provider }, allow_nil: true

  def self.from_omniauth(auth)
    where(uid: auth.uid, provider: auth.provider).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end

  def privacy; end

  def terms; end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    # You should configure your model like this:
    # devise :omniauthable, omniauth_providers: [:twitter]

    # You should also create an action method in this controller like this:
    # def twitter
    # end

    def github
      @user = User.from_omniauth(request.env['omniauth.auth'])
      sign_in_and_redirect @user
    end

    def google_oauth2
      @user = User.from_omniauth(request.env['omniauth.auth'])
      sign_in_and_redirect @user
    end

    def twitter
      @user = User.from_omniauth(request.env['omniauth.auth'])
      sign_in_and_redirect @user
    end

    # More info at:
    # https://github.com/heartcombo/devise#omniauth

    # GET|POST /resource/auth/twitter
    # def passthru
    #   super
    # end

    # GET|POST /users/auth/twitter/callback
    # def failure
    #   super
    # end

    # protected

    # The path used when OmniAuth fails
    # def after_omniauth_failure_path_for(scope)
    #   super(scope)
    # end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def partially_hidden_email(email)
    email.split('@').map do |string|
      string.split('.').map do |letters|
        partially_hidden_string(letters)
      end.join('.')
    end.join('@')
  end

  def partially_hidden_string(string)
    string.length < 3 ? string.gsub(/./, '*') : "#{string[0..1]}#{'*' * string[2..].length}"
  end
end

app/views/home/index.html.erb
<div class="hero py-10">
  <div class="hero-content text-center">
    <div class="max-w-md">
      <% if user_signed_in? %>
        <h1 class="text-5xl font-bold">こんにちは！</h1>
        <p class="py-6"><%= current_user.email %>さん</p>
      <% else %>
        <h1 class="text-5xl font-bold">ようこそ！</h1>
        <p class="py-6">Deviseの検証用のアプリです。EメールもしくはGitHub, Google, Twitterアカウントでログインができます。</p>
        <%= link_to 'アカウント登録', new_user_registration_path, class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/home/privacy.html.erb
<% provide(:title, 'プライバシーポリシー') %>

app/views/home/terms.html.erb
<% provide(:title, '利用規約') %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="light">
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'tailwind', 'inter-font', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="flex flex-col min-h-screen <%= 'static' if flash.any? %>">
    <% unless content_for?(:hide_navbar) %>
      <nav class="navbar bg-base-300 gap-2">
        <div class="flex-none">
          <%= link_to 'トップ', root_path, class: 'btn btn-ghost normal-case text-xl' %>
        </div>
        <div class="flex-1">
          <ul class="menu menu-horizontal p-0">
            <li><%= link_to 'ユーザー一覧', users_path %></li>
            <% if user_signed_in? %>
              <li><%= link_to 'ユーザー編集', edit_user_registration_path %></li>
            <% end %>
          </ul>
        </div>
        <div class="flex-none gap-2">
          <% if user_signed_in? %>
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'btn btn-ghost' %>
          <% else %>
            <%= link_to 'ログイン', new_user_session_path, class: 'btn btn-ghost' %>
            <%= link_to 'アカウント登録', new_user_registration_path, class: 'btn btn-primary' %>
          <% end %>
        </div>
      </nav>
    <% end %>

    <% flash.each do |name, msg| %>
      <div class="absolute right-10 <%= content_for?(:hide_navbar) ? 'top-4' : 'top-20' %>">
        <div class="alert <%= name == 'alert' ? 'alert-error' : 'alert-success' %> shadow-lg px-8">
          <div class="font-medium text-white">
            <% if name == 'alert' %>
              <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
            <% else %>
              <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
            <% end %>
            <span><%= msg %></span>
          </div>
        </div>
      </div>
    <% end %>

    <% if content_for?(:title) %>
      <header>
        <div class="px-6 py-4">
          <h1 class="text-2xl font-bold text-gray-900"><%= content_for(:title) %></h1>
        </div>
      </header>
    <% end %>

    <main class="flex-grow">
      <div class="px-8 py-6">
        <%= yield %>
      </div>
    </main>

    <footer class="footer footer-center p-4 bg-base-200 text-base-content">
      <div class="grid grid-flow-col gap-4">
        <%= link_to 'プライバシーポリシー', privacy_path, class: 'link link-hover' %>
        <%= link_to '利用規約', terms_path, class: 'link link-hover' %>
      </div>
    </footer>
  </body>
</html>

app/views/users/index.html.erb
<% provide(:title, 'ユーザー一覧') %>

<div class="overflow-x-auto">
  <table class="table table-zebra w-full">
    <thead>
      <tr>
        <th class="normal-case">ID</th>
        <th class="normal-case">Email</th>
        <th class="normal-case">confirmed_at</th>
        <th class="normal-case">confirmation_sent_at</th>
        <th class="normal-case">unconfirmed_email</th>
        <th class="normal-case">confirmed?</th>
        <th class="normal-case">Provider</th>
        <th class="normal-case">UID</th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><%= partially_hidden_email(user.email) %></td>
          <td><%= l(user.confirmed_at) if user.confirmed_at %></td>
          <td><%= l(user.confirmation_sent_at) if user.confirmation_sent_at %></td>
          <td><%= partially_hidden_email(user.unconfirmed_email) if user.unconfirmed_email %></td>
          <td><%= user.confirmed? %></td>
          <td><%= user.provider %></td>
          <td><%= partially_hidden_string(user.uid) if user.uid %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>